.TH "define" "23" "August 2015" "Version 20151023" "User Commands"
.SH NAME
define \- Terminal Dictionary
.SH SYNOPSIS
.B define
.RI [ OPTIONS ]
.I KEYWORDS...
.SH DESCRIPTION
.B define
is a command line tool for performing dictionary searches from the terminal.
.SH OPTIONS
.TP
.BI \-h,\--help
Display help and exit.
.TP
.BI \-a,\--audio " keywords"
Audio playback for the the
.I search
result.
.TP
.BI \-t,\--thesaurus " keywords"
Show
.I search
results using thesaurus.
.TP
.BI \-u,\--urban " keywords"
Show
.I search
results using urbandictionary.com.
.TP
.BI \-l,\--local " keywords"
Show
.I search
results using local dict and dictd dictionary.
.TP
.BI \-w,\--wordnet " keywords"
Show
.I search
results using wordnet
.TP
.BI \-k,\--wiktionary " keywords"
Show
.I search
results using wiktionary
.TP
.SH AUTHOR
Written by Johnathan "ShaggyTwoDope" Jenkins <twodopeshaggy@gmail.com> (2015).
.SH REPORTING BUGS
Report bugs to
.I https://github.com/SethDusek/define/issues
.SH COPYRIGHT
Copyright \(co 2015 SethDusek
License BSD.
.PP
